apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: grpc
      port: 9090
      targetPort: 9090
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
        linkerd.io/inject: enabled
        config.linkerd.io/skip-outbound-ports: "4222,8222" #NATS
    spec:
      containers:
        - name: {{ .Values.name }}
          image: cr.selcloud.ru/hack-2025-registry/backend/{{ .Values.name }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          # resources:
          #   limits:
          #     memory: "25048Mi"
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 9090
              protocol: TCP
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: "LD_BIND_NOW"
              value: "1"
            {{- range .Values.env }}
            - name: {{ .name | upper }}
              value: {{ .value }}
            {{- end }}

            {{- range .Values.envFrom }}
            - name: {{ .name | upper }}
              valueFrom:
                configMapKeyRef:
                  name: {{ .from }}
                  key: {{ .key }}
            {{- end }}

            {{- range .Values.secrets }}
            - name: {{ .env | upper }}
              valueFrom:
                secretKeyRef:
                    name: {{ .name }}
                    key: {{ .key }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: zendal-envs
          {{ if eq .Values.disableProbes false }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 2
          {{ end }}
      serviceAccountName: {{ .Values.serviceAccountName | default "default" }}
      imagePullSecrets:
        - name: zendal-regcred